package com.adaidam;

import java.util.Scanner;
import java.util.Arrays;


public class Game {

    public int startGame(){
        Scanner scanner = new Scanner(System.in);

        //start game
        System.out.println("Rock,Paper,Scissors?\n");

        /*create a variable to hold the user response using the Scanner object.
         The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
         */
        int choice = scanner.nextInt();

//        if(userResponse != 1 || userResponse != 2 || userResponse != 3){
//            System.out.println("Invalid response! Please enter 1, 2, or 3.");
//            userResponse = scanner.nextInt();
//        }
        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuChoice = getCPUResponse();

        //compare user and cpu response with each other to decide the winner.
        if(choice == 1 && cpuChoice == 1){
            System.out.println("You chose Rock");
            System.out.println("Computer chose Rock");
            System.out.println("No one wins :(");
            int score = 0;
            return score;
        }
        if(choice == 1 && cpuChoice == 2){
            System.out.println("You chose Rock");
            System.out.println("Computer chose Paper");
            System.out.println("You lose!");
            int score = 0;
            return score;
        }
        if(choice == 1 && cpuChoice == 3){
            System.out.println("You chose Rock");
            System.out.println("Computer chose Scissors");
            System.out.println("You win!");
            int score = 1;
            return score;
        }
        if(choice == 2 && cpuChoice == 2){
            System.out.println("You chose Paper");
            System.out.println("Computer chose Paper");
            System.out.println("No one wins!");
            int score = 0;
            return score;
        }
        if(choice == 1 && cpuChoice == 2){
            System.out.println("You chose Rock");
            System.out.println("Computer chose Paper");
            System.out.println("You lose!");
            int score = 0;
            return score;



    }

    public int getCPUResponse(){
        // Generate random integers in range 1 to 3
        int randomNum = (int) (Math.random() * 3) + 1;
        int cpuResponse = randomNum;
        return cpuResponse;
    }
}
